### PR TITLE
Refactor IntroClassJava

### PR DESCRIPTION
**Pull request by tdurieux**
- Remove projects that does not compile
- Reduce the size of the classname (uses the 8 first charters of the hex ID)

### CODE REVIEW

**Comment by tdurieux** [comment]
@monperrus is it ok for you?

**Comment by monperrus** [comment]
works on Windows?

**Comment by tdurieux** [comment]
I hoop :)

**Comment by tdurieux** [comment]
No that does not work. 
the hex id is too long (the directory not the classname)

**Pull request merged**
